# Generated by Django 3.2.7 on 2022-01-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Sobre mi', 'verbose_name_plural': 'Sobre mi'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Informacion de contacto', 'verbose_name_plural': 'Informacion de contacto'},
        ),
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Fotografía'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Mi nombre'),
        ),
    ]
