# Generated by Django 3.2.7 on 2022-01-03 04:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_about_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='payment',
            new_name='price_per_hour',
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
