# Generated by Django 3.2.7 on 2022-01-03 04:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220102_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
